#!/usr/bin/env ruby

check :no_unprocessed_erb do
  self.output_filenames.each do |fn|
    if fn =~ /html$/ && File.read(fn).match(/<%/)
      self.add_issue("erb detected", :subject => fn)
    end
  end
end

check :valid_sitemap do
  require 'nokogiri'

  xsd = Nokogiri::XML::Schema(File.read('misc/sitemap.xsd'))
  doc = Nokogiri::XML(File.read('output/sitemap.xml'))

  unless xsd.valid?(doc)
    self.add_issue("sitemap does not adhere to XML schema", :subject => 'output/sitemap.xml')
  end
end

check :no_smartness_in_kbd do
  self.output_filenames.each do |fn|
    if fn =~ /html$/ && File.read(fn).match(/<kbd>[^<]*[–—][^<]*<\/kbd>/)
      self.add_issue("smartness in kbd elem detected", :subject => fn)
    end
  end
end

deploy_check :ilinks
deploy_check :stale
deploy_check :no_unprocessed_erb
deploy_check :valid_sitemap
deploy_check :no_smartness_in_kbd
